language: node_js
node_js:
  - "14.5"
dist: trusty
sudo: required

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

branches:
  only:
  - main

before_script:
  - npm install -g @angular/cli@10.1.6

install:
- npm ci

# keep the npm cache around to speed up installs
cache:
  directories:
  - "$HOME/.npm"

script:
- ng lint
- npm run test-headless
- ng build --prod --aot